# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa5575031c31cdc26676c4449cade9d2b450c993422059d87690b7400ebfffaf463cda1e3bd145d55d54c98201fd062e87f0f89f3bddd80d11ca8589fe431e47

test:
  secret_key_base: 8f506cdde0015468b5b394a2595ecdb6f97735d53d89fd8aba1a08eaf5e9331dbc8ef7393a24bf03bbc5b2b94343bdcf294c415be1de08ed199f206e455d54d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
